language: node_js
node_js: 
  - "4.1"
services: mongodb
before_script:
  - sleep 10
  - npm install -g gulp
  - mongod --version
  - mongo --version
script: 
  - git clone --branch=master https://github.com/cuponthetop/sadanghaeng_auth.git
  - cd sadanghaeng_auth
  - npm install
  - node test/init/test-init.js
  - node lib/server/server.js &
  - cd ..
  - node test/init/test-init.js
  - node lib/server/server.js &
  - gulp test
env:
  - NODE_ENV=test CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8